name: Playright

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Enter Github Url'
        required: true
  
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setting the environment
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Installing all dependencies
      run: npm install
      
    - name: Getting Started
      run: node playright.js
      env:
          CI: true
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          title: ${{ github.event.inputs.title }}
    
